server:
  port: 10003
spring:
  application:
    name: springcloud-eureka-cluster
  profiles: server3
eureka:
  instance:
    hostname: server3
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://server1:10001/eureka/,http://server2:10002/eureka/