server:
  port: 10001
spring:
  application:
    name: springcloud-eureka-cluster
  profiles: server1
eureka:
  instance:
    hostname: server1
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://server2:10002/eureka/,http://server3:10003/eureka/