eureka:
  client:
    service-url:
      defaultZone: http://server1:10001/eureka/,http://server2:10002/eureka/,http://server3:10003/eureka/

spring:
  redis:
    database: 1
    host: 172.16.144.67
    port: 11204
    password: aiolosREDIS1204285.