server:
  port: 7070

spring:
  application:
    name: springcloud-zuul

eureka:
  server:
    hostname: localhost
    port: 7000
  client:
    service-url:
      defaultZone: http://server-7001:7001/eureka/,http://server-7002:7002/eureka/,http://server-7003:7003/eureka/

# 路由规则：http://[网关地址]:[端口号]/[prefix]/[微服务实例名称]/[请求地址路径]
zuul:
  prefix: /api                           # 请求前缀
  routes:
    news-service-article: /news-service-article/**    # 只要路由id和微服务实例id相同，就可以简写成这样去配置路由规则
#    news-service-article:               # 配置微服务的路由id，微服务的实例id
#      path: /news-service-article/**    # 请求路径（前缀）
#      service-id: news-service-article  # 通过微服务id在eureka注册中心里的地址，用这个就不用url: http://localhost:8001了
#      url: http://localhost:8001        # 请求转发到指定的微服务所在的ip地址，但是不稳定，端口号改了这里也得改
