server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1
spring:
  application:
    name: news-user
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  resources:
    add-mappings: false   # true: 如果所有的controller都没有命中，则使用默认的静态资源处理器做匹配，匹配不上和false一样被全局异常捕获
  mvc:
    throw-exception-if-no-handler-found: true    #找不到handler（所有匹配的controller）就抛出对应的异常
mapper:
  mappers: com.aiolos.news.utils.MyMapper
  not-empty: false        # 在进行数据库操作的时候，判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL
# 分页插件配置
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启mybatis日志
  type-aliases-package: com.aiolos.news.pojo
  mapper-locations: classpath:mapper/*.xml