server:
  port: 8111
spring:
  redis:
    database: 1
    host: 172.16.144.67
    port: 11204
    password: aiolosREDIS1204285.
  rabbitmq:
    host: 120.26.73.8
    username: aiolos
    password: aiolos
    virtual-host: news
  data:
    mongodb:
      uri: mongodb://aiolos:aiolos@127.0.0.1:27017
      database: news
  zipkin:
    base-url: http://120.26.73.8:9411/   # 配置zipkin采集的服务地址，数据会发送到这里
    sender:
      type: web       # 数据采集的传输通信方式，web：http的形式
  sleuth:
    sampler:
      probability: 0.8    # 数据采样比例（百分数），0-1
# 设置域名，在java代码中会获取
website:
  domain-name: aiolosxhx.com

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://server1:10001/eureka/,http://server2:10002/eureka/,http://server3:10003/eureka/